"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { getSupabaseBrowser } from "@/lib/supabase/browser";
import { formatPKR } from "@/lib/data";

type Order = { id: string; order_number: string; total: number; order_status: string; created_at: string };
export function AccountPanel() {
    const router = useRouter(); const [email, setEmail] = useState(""); const [name, setName] = useState(""); const [phone, setPhone] = useState(""); const [orders, setOrders] = useState<Order[]>([]); const [isAdmin, setIsAdmin] = useState(false); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
    useEffect(() => { const supabase = getSupabaseBrowser(); if (!supabase) { Promise.resolve().then(() => { setError("Account services are not configured."); setLoading(false); }); return; } (async () => { const { data: { user } } = await supabase.auth.getUser(); if (!user) { router.replace("/login?next=/account"); return; } setEmail(user.email ?? ""); const [{ data: profile, error: profileError }, { data: ownOrders, error: ordersError }] = await Promise.all([supabase.from("profiles").select("full_name,phone,role").eq("id", user.id).single(), supabase.from("orders").select("id,order_number,total,order_status,created_at").eq("user_id", user.id).order("created_at", { ascending: false })]); if (profileError && profileError.code !== "PGRST116") setError(profileError.message); if (ordersError) setError(ordersError.message); setName(profile?.full_name ?? ""); setPhone(profile?.phone ?? ""); setIsAdmin(profile?.role === "admin"); setOrders((ownOrders as Order[]) ?? []); setLoading(false); })().catch((caught) => { if (process.env.NODE_ENV !== "production") console.error("Account load failed:", caught); setError("We could not load your account."); setLoading(false); }); }, [router]);
    async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const supabase = getSupabaseBrowser(); if (!supabase) return; const { data: { user } } = await supabase.auth.getUser(); if (!user) return; setSaving(true); const { error: saveError } = await supabase.from("profiles").update({ full_name: name, phone }).eq("id", user.id); if (saveError) setError(saveError.message); setSaving(false); }
    async function signOut() { const supabase = getSupabaseBrowser(); await supabase?.auth.signOut(); router.replace("/"); router.refresh(); }
    if (loading) return <p className="eyebrow">Loading your account...</p>;
    return <div className="account-grid"><section className="form-panel"><p className="eyebrow">Profile</p><h2>{name || email.split("@")[0]}</h2><p>{email}</p><form onSubmit={save}><div className="field"><label htmlFor="account-name">Full name</label><input id="account-name" value={name} onChange={(event) => setName(event.target.value)} /></div><div className="field"><label htmlFor="account-phone">Phone</label><input id="account-phone" value={phone} onChange={(event) => setPhone(event.target.value)} /></div><button className="button" type="submit" disabled={saving}>{saving ? "Saving..." : "Save profile"}</button></form>{isAdmin && <Link className="button secondary" href="/admin">Admin dashboard</Link>}<button className="remove" type="button" onClick={signOut}>Sign out</button>{error && <p role="alert" style={{ color: "#a33" }}>{error}</p>}</section><section><p className="eyebrow">Order history</p><h2>Previous orders.</h2>{orders.length ? orders.map((order) => <div className="summary form-panel" key={order.id}><div className="summary-row"><span>{order.order_number}</span><strong>{formatPKR(Number(order.total))}</strong></div><div className="summary-row"><span>{new Date(order.created_at).toLocaleDateString("en-PK")}</span><span>{order.order_status}</span></div></div>) : <p className="detail-description">Your completed orders will appear here.</p>}</section></div>;
}
