"use client";

import { useMemo, useState } from "react";

type Row = Record<string, string>;
const fields = [["name", "Product Name"], ["description", "Description"], ["price", "Selling Price"], ["costPrice", "Cost Price"], ["category", "Category"], ["sku", "SKU"], ["stock", "Stock Quantity"], ["image", "Image URL"], ["supplierId", "Supplier Product ID"], ["supplierUrl", "Supplier URL"]] as const;

export function AdminImport() {
    const [rows, setRows] = useState<Row[]>([]); const [columns, setColumns] = useState<string[]>([]); const [mapping, setMapping] = useState<Record<string, string>>({}); const [file, setFile] = useState<File | null>(null); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [pricing, setPricing] = useState({ useImported: true, profitType: "percentage", profit: "30", shipping: "200", other: "0", rounding: "1" });
    const suggested = useMemo(() => { const result = { ...mapping }; fields.forEach(([key, label]) => { result[key] ||= columns.find((column) => column.toLowerCase().includes(label.toLowerCase().split(" ")[0])) ?? ""; }); return result; }, [columns, mapping]);
    async function choose(selected: File) { setFile(selected); setError(""); const extension = selected.name.toLowerCase().split(".").pop(); if (!extension || !["csv", "xlsx", "xls"].includes(extension)) { setError("Only CSV and Excel files are supported."); return; } try { const XLSX = await import("xlsx"); const book = XLSX.read(await selected.arrayBuffer(), { type: "array" }); const json = XLSX.utils.sheet_to_json<Row>(book.Sheets[book.SheetNames[0]], { defval: "" }); const headers = json.length ? Object.keys(json[0]) : []; setRows(json.slice(0, 8)); setColumns(headers); setMapping({}); } catch { setError("We could not preview this spreadsheet."); } }
    async function submit() { if (!file) { setError("Choose a file first."); return; } setError(""); setMessage("Importing products..."); const data = new FormData(); data.append("file", file); data.append("mapping", JSON.stringify(suggested)); data.append("pricing", JSON.stringify({ ...pricing, profit: Number(pricing.profit), shipping: Number(pricing.shipping), other: Number(pricing.other), rounding: Number(pricing.rounding) })); data.append("duplicateMode", "skip"); data.append("sourceType", "markaz"); try { const response = await fetch("/api/admin/import", { method: "POST", body: data }); const result = await response.json(); if (!response.ok) setError(result.error ?? "Import failed."); else setMessage(`Import complete: ${result.imported} imported, ${result.failed} failed.`); } catch { setError("We could not connect to the import service."); } }
    return <div className="admin-import"><div className="admin-import-upload"><label htmlFor="import-file">Drop a CSV or Excel file here, or choose a file</label><input id="import-file" type="file" accept=".csv,.xlsx,.xls" onChange={(event) => { const selected = event.target.files?.[0]; if (selected) choose(selected); }} />{file && <p>{file.name}</p>}</div>{columns.length > 0 && <><div className="admin-import-section"><h2>Column mapping</h2>{fields.map(([key, label]) => <label className="mapping-row" key={key}><span>{label}{["name", "sku"].includes(key) && " *"}</span><select value={suggested[key] ?? ""} onChange={(event) => setMapping({ ...mapping, [key]: event.target.value })}><option value="">Not mapped</option>{columns.map((column) => <option key={column}>{column}</option>)}</select></label>)}</div><div className="admin-import-section"><h2>Pricing configuration</h2><label><input type="checkbox" checked={pricing.useImported} onChange={(event) => setPricing({ ...pricing, useImported: event.target.checked })} /> Use imported selling price</label>{!pricing.useImported && <div className="pricing-grid"><select value={pricing.profitType} onChange={(event) => setPricing({ ...pricing, profitType: event.target.value })}><option value="percentage">Profit percentage</option><option value="fixed">Fixed profit</option></select><input placeholder="Profit" value={pricing.profit} onChange={(event) => setPricing({ ...pricing, profit: event.target.value })} /><input placeholder="Shipping cost" value={pricing.shipping} onChange={(event) => setPricing({ ...pricing, shipping: event.target.value })} /><input placeholder="Other costs" value={pricing.other} onChange={(event) => setPricing({ ...pricing, other: event.target.value })} /><select value={pricing.rounding} onChange={(event) => setPricing({ ...pricing, rounding: event.target.value })}><option value="1">No rounding</option><option value="10">Nearest 10</option><option value="50">Nearest 50</option><option value="100">Nearest 100</option></select></div>}</div><div className="admin-import-section"><h2>Preview</h2><div className="admin-preview"><table><thead><tr>{columns.map((column) => <th key={column}>{column}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index}>{columns.map((column) => <td key={column}>{row[column]}</td>)}</tr>)}</tbody></table></div><button className="button" onClick={submit}>Import selected products</button></div></>}{error && <p role="alert" className="admin-error">{error}</p>}{message && <p role="status" className="admin-success">{message}</p>}</div>;
}
