import Image from "next/image";
import Link from "next/link";
import { Check, Star, Truck } from "lucide-react";
import { getProductBySlug, getProducts } from "@/lib/catalog";
import { formatPKR } from "@/lib/data";
import { ProductActions } from "@/components/product-actions";

export const dynamic = "force-dynamic";

export default async function ProductPage({ params }: { params: Promise<{ slug: string }> }) { const product = await getProductBySlug((await params).slug); if (!product) return <div className="shell page-intro"><h1>Product not found.</h1><Link className="button" href="/shop">Back to shop</Link></div>; const related = (await getProducts()).filter((item) => item.id !== product.id).slice(0, 4); return <><section className="product-detail"><div className="shell detail-grid"><div className="detail-image"><Image src={product.image} alt={product.name} fill priority sizes="(max-width: 800px) 100vw, 50vw" /></div><div className="detail-copy"><p className="eyebrow">{product.category.replace("-", " ")}</p><h1>{product.name}</h1>{product.reviews > 0 && <div className="rating"><Star size={15} fill="currentColor" /> {product.rating} · {product.reviews} reviews</div>}<p className="detail-price">{formatPKR(product.price)} {product.compareAtPrice && <del>{formatPKR(product.compareAtPrice)}</del>}</p><p className="detail-description">{product.description}</p><p className="stock">{product.stock > 0 ? `In stock · ${product.stock} available` : "Currently out of stock"}</p><div className="button-row"><ProductActions product={product} /></div><hr /><div className="detail-points"><span><Check size={16} /> Quality checked before dispatch</span><span><Truck size={16} /> Cash on delivery across Pakistan</span><span><Check size={16} /> Easy returns within 7 days</span></div></div></div></section><section className="section" style={{ paddingTop: 0 }}><div className="shell"><div className="section-head"><h2>You may also like.</h2></div><div className="product-grid">{related.map((item) => <Link href={`/product/${item.slug}`} key={item.id}><Image src={item.image} alt={item.name} width={400} height={450} style={{ width: "100%", height: "auto", objectFit: "cover" }} /><strong style={{ display: "block", marginTop: 10 }}>{item.name}</strong></Link>)}</div></div></section></>; }
